// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file common/package/package_v1.proto (package common.package.v1, edition 2023)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Timestamp } from "../../third_party/google/protobuf/timestamp_pb";
import { file_third_party_google_protobuf_timestamp } from "../../third_party/google/protobuf/timestamp_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/package/package_v1.proto.
 */
export const file_common_package_package_v1: GenFile = /*@__PURE__*/
  fileDesc("Ch9jb21tb24vcGFja2FnZS9wYWNrYWdlX3YxLnByb3RvEhFjb21tb24ucGFja2FnZS52MSJNCg9QYWNrYWdlTWV0YWRhdGESCgoCaWQYASABKAkSLgoKYnVpbGRfdGltZRgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAiUAoKQXBwUGFja2FnZRIMCgRuYW1lGAEgASgJEjQKCG1ldGFkYXRhGAIgASgLMiIuY29tbW9uLnBhY2thZ2UudjEuUGFja2FnZU1ldGFkYXRhYghlZGl0aW9uc3DoBw", [file_third_party_google_protobuf_timestamp]);

/**
 * @generated from message common.package.v1.PackageMetadata
 */
export type PackageMetadata = Message<"common.package.v1.PackageMetadata"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: google.protobuf.Timestamp build_time = 2;
   */
  buildTime?: Timestamp;
};

/**
 * Describes the message common.package.v1.PackageMetadata.
 * Use `create(PackageMetadataSchema)` to create a new message.
 */
export const PackageMetadataSchema: GenMessage<PackageMetadata> = /*@__PURE__*/
  messageDesc(file_common_package_package_v1, 0);

/**
 * ○ Version ID
 * ○ Data and time package was built
 * ○ Builder
 * ○ Size
 * ○ Labels
 * ○ Date of last fetch
 * ○ Durability
 * ○ Expiration
 * ○ ACL
 *
 * @generated from message common.package.v1.AppPackage
 */
export type AppPackage = Message<"common.package.v1.AppPackage"> & {
  /**
   * App package name.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Build time metadata.
   *
   * @generated from field: common.package.v1.PackageMetadata metadata = 2;
   */
  metadata?: PackageMetadata;
};

/**
 * Describes the message common.package.v1.AppPackage.
 * Use `create(AppPackageSchema)` to create a new message.
 */
export const AppPackageSchema: GenMessage<AppPackage> = /*@__PURE__*/
  messageDesc(file_common_package_package_v1, 1);

