on: [push]
jobs:
  docker:
    runs-on: docker
    container:
      image: docker:28.0.2-cli
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node
        run: |
          apk add --update nodejs npm

      # - name: Set up node
      #   uses: https://code.forgejo.org/actions/setup-node@v4
      #   with:
      #     node-version: '22.x'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login local repo
        uses: docker/login-action@v3
        with:
          registry: forgejo.parrajustin.com
          username: jrparra
          password: ${{ secrets.FORGEJO_TOKEN }}

      - name: Build
        run: |
          cd docker
          docker build -t forgejo.parrajustin.com/jrparra/bazelisk:latest -f ./bazelisk.Dockerfile .

      - name: Push container
        run: |
          docker push forgejo.parrajustin.com/jrparra/bazelisk:latest
          